rest apigateway to httpapi

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -102,10 +102,17 @@ jobs:
           SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}
         run: |
           cd infra
-          npx dotenv -e ../.env -- serverless deploy > deploy_output.txt
-          cat deploy_output.txt
-          API_URL=$(grep -o 'https://[a-z0-9-]*\.execute-api\.[a-z0-9-]*\.amazonaws\.com/[a-zA-Z0-9_-]*/' deploy_output.txt | head -n 1)
-          echo "La URL extraída es: $API_URL"
+          npx dotenv -e ../.env -- serverless deploy
+          INFO_OUTPUT=$(npx dotenv -e ../.env -- serverless info)
+          echo "$INFO_OUTPUT"
+          
+          API_URL=$(echo "$INFO_OUTPUT" | grep -o 'https://[a-zA-Z0-9-]*\.execute-api\.[a-zA-Z0-9-]*\.amazonaws\.com/[a-zA-Z0-9_-]*/' | head -n 1)
+          
+          if [ -z "$API_URL" ]; then
+            echo "❌ Error: No se pudo obtener la URL del endpoint."
+            exit 1
+          fi
+          
           echo "api_url=$API_URL" >> $GITHUB_OUTPUT
 
       - name: Update README.md
